//
// Created by user on 12/21/15.
//

#ifndef POCOSERVER_VERIFICATIONBEHAVIOURCOMMUNITY_H
#define POCOSERVER_VERIFICATIONBEHAVIOURCOMMUNITY_H


class VerificationBehaviourCommunity {

};


#endif //POCOSERVER_VERIFICATIONBEHAVIOURCOMMUNITY_H
